#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_Employee_Management
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="EmployeeManagement")]
	public partial class Employee_ManagementDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttbChamCong(tbChamCong instance);
    partial void UpdatetbChamCong(tbChamCong instance);
    partial void DeletetbChamCong(tbChamCong instance);
    partial void InserttbChucVu(tbChucVu instance);
    partial void UpdatetbChucVu(tbChucVu instance);
    partial void DeletetbChucVu(tbChucVu instance);
    partial void InserttbDanhGia(tbDanhGia instance);
    partial void UpdatetbDanhGia(tbDanhGia instance);
    partial void DeletetbDanhGia(tbDanhGia instance);
    partial void InserttbDuAn(tbDuAn instance);
    partial void UpdatetbDuAn(tbDuAn instance);
    partial void DeletetbDuAn(tbDuAn instance);
    partial void InserttbNhanVien(tbNhanVien instance);
    partial void UpdatetbNhanVien(tbNhanVien instance);
    partial void DeletetbNhanVien(tbNhanVien instance);
    partial void InserttbPhongBan(tbPhongBan instance);
    partial void UpdatetbPhongBan(tbPhongBan instance);
    partial void DeletetbPhongBan(tbPhongBan instance);
    #endregion
		
		public Employee_ManagementDataContext() : 
				base(global::project_Employee_Management.Properties.Settings.Default.EmployeeManagementConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Employee_ManagementDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Employee_ManagementDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Employee_ManagementDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Employee_ManagementDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbChamCong> tbChamCongs
		{
			get
			{
				return this.GetTable<tbChamCong>();
			}
		}
		
		public System.Data.Linq.Table<tbChucVu> tbChucVus
		{
			get
			{
				return this.GetTable<tbChucVu>();
			}
		}
		
		public System.Data.Linq.Table<tbDanhGia> tbDanhGias
		{
			get
			{
				return this.GetTable<tbDanhGia>();
			}
		}
		
		public System.Data.Linq.Table<tbDuAn> tbDuAns
		{
			get
			{
				return this.GetTable<tbDuAn>();
			}
		}
		
		public System.Data.Linq.Table<tbNhanVien> tbNhanViens
		{
			get
			{
				return this.GetTable<tbNhanVien>();
			}
		}
		
		public System.Data.Linq.Table<tbPhongBan> tbPhongBans
		{
			get
			{
				return this.GetTable<tbPhongBan>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbChamCong")]
	public partial class tbChamCong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maNgay;
		
		private System.Nullable<int> _maNhanVien;
		
		private System.Nullable<System.DateTime> _ngaylamviec;
		
		private System.Nullable<byte> _trangthai;
		
		private System.Nullable<bool> _fulltime;
		
		private EntityRef<tbNhanVien> _tbNhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaNgayChanging(int value);
    partial void OnmaNgayChanged();
    partial void OnmaNhanVienChanging(System.Nullable<int> value);
    partial void OnmaNhanVienChanged();
    partial void OnngaylamviecChanging(System.Nullable<System.DateTime> value);
    partial void OnngaylamviecChanged();
    partial void OntrangthaiChanging(System.Nullable<byte> value);
    partial void OntrangthaiChanged();
    partial void OnfulltimeChanging(System.Nullable<bool> value);
    partial void OnfulltimeChanged();
    #endregion
		
		public tbChamCong()
		{
			this._tbNhanVien = default(EntityRef<tbNhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNgay", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maNgay
		{
			get
			{
				return this._maNgay;
			}
			set
			{
				if ((this._maNgay != value))
				{
					this.OnmaNgayChanging(value);
					this.SendPropertyChanging();
					this._maNgay = value;
					this.SendPropertyChanged("maNgay");
					this.OnmaNgayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNhanVien", DbType="Int")]
		public System.Nullable<int> maNhanVien
		{
			get
			{
				return this._maNhanVien;
			}
			set
			{
				if ((this._maNhanVien != value))
				{
					if (this._tbNhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._maNhanVien = value;
					this.SendPropertyChanged("maNhanVien");
					this.OnmaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaylamviec", DbType="Date")]
		public System.Nullable<System.DateTime> ngaylamviec
		{
			get
			{
				return this._ngaylamviec;
			}
			set
			{
				if ((this._ngaylamviec != value))
				{
					this.OnngaylamviecChanging(value);
					this.SendPropertyChanging();
					this._ngaylamviec = value;
					this.SendPropertyChanged("ngaylamviec");
					this.OnngaylamviecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangthai", DbType="TinyInt")]
		public System.Nullable<byte> trangthai
		{
			get
			{
				return this._trangthai;
			}
			set
			{
				if ((this._trangthai != value))
				{
					this.OntrangthaiChanging(value);
					this.SendPropertyChanging();
					this._trangthai = value;
					this.SendPropertyChanged("trangthai");
					this.OntrangthaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fulltime", DbType="Bit")]
		public System.Nullable<bool> fulltime
		{
			get
			{
				return this._fulltime;
			}
			set
			{
				if ((this._fulltime != value))
				{
					this.OnfulltimeChanging(value);
					this.SendPropertyChanging();
					this._fulltime = value;
					this.SendPropertyChanged("fulltime");
					this.OnfulltimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbNhanVien_tbChamCong", Storage="_tbNhanVien", ThisKey="maNhanVien", OtherKey="maNhanVien", IsForeignKey=true)]
		public tbNhanVien tbNhanVien
		{
			get
			{
				return this._tbNhanVien.Entity;
			}
			set
			{
				tbNhanVien previousValue = this._tbNhanVien.Entity;
				if (((previousValue != value) 
							|| (this._tbNhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbNhanVien.Entity = null;
						previousValue.tbChamCongs.Remove(this);
					}
					this._tbNhanVien.Entity = value;
					if ((value != null))
					{
						value.tbChamCongs.Add(this);
						this._maNhanVien = value.maNhanVien;
					}
					else
					{
						this._maNhanVien = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbNhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbChucVu")]
	public partial class tbChucVu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maChucVu;
		
		private string _tenChucVu;
		
		private System.Nullable<double> _luongcung;
		
		private System.Nullable<int> _huongDoanhSo;
		
		private EntitySet<tbNhanVien> _tbNhanViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaChucVuChanging(int value);
    partial void OnmaChucVuChanged();
    partial void OntenChucVuChanging(string value);
    partial void OntenChucVuChanged();
    partial void OnluongcungChanging(System.Nullable<double> value);
    partial void OnluongcungChanged();
    partial void OnhuongDoanhSoChanging(System.Nullable<int> value);
    partial void OnhuongDoanhSoChanged();
    #endregion
		
		public tbChucVu()
		{
			this._tbNhanViens = new EntitySet<tbNhanVien>(new Action<tbNhanVien>(this.attach_tbNhanViens), new Action<tbNhanVien>(this.detach_tbNhanViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maChucVu", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maChucVu
		{
			get
			{
				return this._maChucVu;
			}
			set
			{
				if ((this._maChucVu != value))
				{
					this.OnmaChucVuChanging(value);
					this.SendPropertyChanging();
					this._maChucVu = value;
					this.SendPropertyChanged("maChucVu");
					this.OnmaChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenChucVu", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tenChucVu
		{
			get
			{
				return this._tenChucVu;
			}
			set
			{
				if ((this._tenChucVu != value))
				{
					this.OntenChucVuChanging(value);
					this.SendPropertyChanging();
					this._tenChucVu = value;
					this.SendPropertyChanged("tenChucVu");
					this.OntenChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_luongcung", DbType="Float")]
		public System.Nullable<double> luongcung
		{
			get
			{
				return this._luongcung;
			}
			set
			{
				if ((this._luongcung != value))
				{
					this.OnluongcungChanging(value);
					this.SendPropertyChanging();
					this._luongcung = value;
					this.SendPropertyChanged("luongcung");
					this.OnluongcungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_huongDoanhSo", DbType="Int")]
		public System.Nullable<int> huongDoanhSo
		{
			get
			{
				return this._huongDoanhSo;
			}
			set
			{
				if ((this._huongDoanhSo != value))
				{
					this.OnhuongDoanhSoChanging(value);
					this.SendPropertyChanging();
					this._huongDoanhSo = value;
					this.SendPropertyChanged("huongDoanhSo");
					this.OnhuongDoanhSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbChucVu_tbNhanVien", Storage="_tbNhanViens", ThisKey="maChucVu", OtherKey="maChucVu")]
		public EntitySet<tbNhanVien> tbNhanViens
		{
			get
			{
				return this._tbNhanViens;
			}
			set
			{
				this._tbNhanViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbNhanViens(tbNhanVien entity)
		{
			this.SendPropertyChanging();
			entity.tbChucVu = this;
		}
		
		private void detach_tbNhanViens(tbNhanVien entity)
		{
			this.SendPropertyChanging();
			entity.tbChucVu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbDanhGia")]
	public partial class tbDanhGia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maDanhGia;
		
		private int _maNhanVien;
		
		private string _mucDanhGia;
		
		private System.DateTime _ngayDanhGia;
		
		private string _ghichu;
		
		private EntityRef<tbNhanVien> _tbNhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaDanhGiaChanging(int value);
    partial void OnmaDanhGiaChanged();
    partial void OnmaNhanVienChanging(int value);
    partial void OnmaNhanVienChanged();
    partial void OnmucDanhGiaChanging(string value);
    partial void OnmucDanhGiaChanged();
    partial void OnngayDanhGiaChanging(System.DateTime value);
    partial void OnngayDanhGiaChanged();
    partial void OnghichuChanging(string value);
    partial void OnghichuChanged();
    #endregion
		
		public tbDanhGia()
		{
			this._tbNhanVien = default(EntityRef<tbNhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maDanhGia", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maDanhGia
		{
			get
			{
				return this._maDanhGia;
			}
			set
			{
				if ((this._maDanhGia != value))
				{
					this.OnmaDanhGiaChanging(value);
					this.SendPropertyChanging();
					this._maDanhGia = value;
					this.SendPropertyChanged("maDanhGia");
					this.OnmaDanhGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNhanVien", DbType="Int NOT NULL")]
		public int maNhanVien
		{
			get
			{
				return this._maNhanVien;
			}
			set
			{
				if ((this._maNhanVien != value))
				{
					if (this._tbNhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._maNhanVien = value;
					this.SendPropertyChanged("maNhanVien");
					this.OnmaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mucDanhGia", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string mucDanhGia
		{
			get
			{
				return this._mucDanhGia;
			}
			set
			{
				if ((this._mucDanhGia != value))
				{
					this.OnmucDanhGiaChanging(value);
					this.SendPropertyChanging();
					this._mucDanhGia = value;
					this.SendPropertyChanged("mucDanhGia");
					this.OnmucDanhGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayDanhGia", DbType="Date NOT NULL")]
		public System.DateTime ngayDanhGia
		{
			get
			{
				return this._ngayDanhGia;
			}
			set
			{
				if ((this._ngayDanhGia != value))
				{
					this.OnngayDanhGiaChanging(value);
					this.SendPropertyChanging();
					this._ngayDanhGia = value;
					this.SendPropertyChanged("ngayDanhGia");
					this.OnngayDanhGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghichu", DbType="NVarChar(250)")]
		public string ghichu
		{
			get
			{
				return this._ghichu;
			}
			set
			{
				if ((this._ghichu != value))
				{
					this.OnghichuChanging(value);
					this.SendPropertyChanging();
					this._ghichu = value;
					this.SendPropertyChanged("ghichu");
					this.OnghichuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbNhanVien_tbDanhGia", Storage="_tbNhanVien", ThisKey="maNhanVien", OtherKey="maNhanVien", IsForeignKey=true)]
		public tbNhanVien tbNhanVien
		{
			get
			{
				return this._tbNhanVien.Entity;
			}
			set
			{
				tbNhanVien previousValue = this._tbNhanVien.Entity;
				if (((previousValue != value) 
							|| (this._tbNhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbNhanVien.Entity = null;
						previousValue.tbDanhGias.Remove(this);
					}
					this._tbNhanVien.Entity = value;
					if ((value != null))
					{
						value.tbDanhGias.Add(this);
						this._maNhanVien = value.maNhanVien;
					}
					else
					{
						this._maNhanVien = default(int);
					}
					this.SendPropertyChanged("tbNhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbDuAn")]
	public partial class tbDuAn : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maDuAn;
		
		private string _tenDuAn;
		
		private System.Nullable<int> _maNhanVien;
		
		private double _giatri;
		
		private System.Nullable<bool> _trangthai;
		
		private EntityRef<tbNhanVien> _tbNhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaDuAnChanging(int value);
    partial void OnmaDuAnChanged();
    partial void OntenDuAnChanging(string value);
    partial void OntenDuAnChanged();
    partial void OnmaNhanVienChanging(System.Nullable<int> value);
    partial void OnmaNhanVienChanged();
    partial void OngiatriChanging(double value);
    partial void OngiatriChanged();
    partial void OntrangthaiChanging(System.Nullable<bool> value);
    partial void OntrangthaiChanged();
    #endregion
		
		public tbDuAn()
		{
			this._tbNhanVien = default(EntityRef<tbNhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maDuAn", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maDuAn
		{
			get
			{
				return this._maDuAn;
			}
			set
			{
				if ((this._maDuAn != value))
				{
					this.OnmaDuAnChanging(value);
					this.SendPropertyChanging();
					this._maDuAn = value;
					this.SendPropertyChanged("maDuAn");
					this.OnmaDuAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenDuAn", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string tenDuAn
		{
			get
			{
				return this._tenDuAn;
			}
			set
			{
				if ((this._tenDuAn != value))
				{
					this.OntenDuAnChanging(value);
					this.SendPropertyChanging();
					this._tenDuAn = value;
					this.SendPropertyChanged("tenDuAn");
					this.OntenDuAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNhanVien", DbType="Int")]
		public System.Nullable<int> maNhanVien
		{
			get
			{
				return this._maNhanVien;
			}
			set
			{
				if ((this._maNhanVien != value))
				{
					if (this._tbNhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._maNhanVien = value;
					this.SendPropertyChanged("maNhanVien");
					this.OnmaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giatri", DbType="Float NOT NULL")]
		public double giatri
		{
			get
			{
				return this._giatri;
			}
			set
			{
				if ((this._giatri != value))
				{
					this.OngiatriChanging(value);
					this.SendPropertyChanging();
					this._giatri = value;
					this.SendPropertyChanged("giatri");
					this.OngiatriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangthai", DbType="Bit")]
		public System.Nullable<bool> trangthai
		{
			get
			{
				return this._trangthai;
			}
			set
			{
				if ((this._trangthai != value))
				{
					this.OntrangthaiChanging(value);
					this.SendPropertyChanging();
					this._trangthai = value;
					this.SendPropertyChanged("trangthai");
					this.OntrangthaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbNhanVien_tbDuAn", Storage="_tbNhanVien", ThisKey="maNhanVien", OtherKey="maNhanVien", IsForeignKey=true)]
		public tbNhanVien tbNhanVien
		{
			get
			{
				return this._tbNhanVien.Entity;
			}
			set
			{
				tbNhanVien previousValue = this._tbNhanVien.Entity;
				if (((previousValue != value) 
							|| (this._tbNhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbNhanVien.Entity = null;
						previousValue.tbDuAns.Remove(this);
					}
					this._tbNhanVien.Entity = value;
					if ((value != null))
					{
						value.tbDuAns.Add(this);
						this._maNhanVien = value.maNhanVien;
					}
					else
					{
						this._maNhanVien = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbNhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbNhanVien")]
	public partial class tbNhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maNhanVien;
		
		private string _tenNV;
		
		private System.DateTime _ngaysinh;
		
		private string _email;
		
		private System.Nullable<int> _sdt;
		
		private string _diachi;
		
		private string _taikhoan;
		
		private string _matkhau;
		
		private System.Nullable<int> _maChucVu;
		
		private System.Nullable<int> _maPhongBan;
		
		private System.Nullable<bool> _hoatdong;
		
		private System.Data.Linq.Binary _anh;
		
		private EntitySet<tbChamCong> _tbChamCongs;
		
		private EntitySet<tbDanhGia> _tbDanhGias;
		
		private EntitySet<tbDuAn> _tbDuAns;
		
		private EntityRef<tbChucVu> _tbChucVu;
		
		private EntityRef<tbPhongBan> _tbPhongBan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaNhanVienChanging(int value);
    partial void OnmaNhanVienChanged();
    partial void OntenNVChanging(string value);
    partial void OntenNVChanged();
    partial void OnngaysinhChanging(System.DateTime value);
    partial void OnngaysinhChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnsdtChanging(System.Nullable<int> value);
    partial void OnsdtChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    partial void OntaikhoanChanging(string value);
    partial void OntaikhoanChanged();
    partial void OnmatkhauChanging(string value);
    partial void OnmatkhauChanged();
    partial void OnmaChucVuChanging(System.Nullable<int> value);
    partial void OnmaChucVuChanged();
    partial void OnmaPhongBanChanging(System.Nullable<int> value);
    partial void OnmaPhongBanChanged();
    partial void OnhoatdongChanging(System.Nullable<bool> value);
    partial void OnhoatdongChanged();
    partial void OnanhChanging(System.Data.Linq.Binary value);
    partial void OnanhChanged();
    #endregion
		
		public tbNhanVien()
		{
			this._tbChamCongs = new EntitySet<tbChamCong>(new Action<tbChamCong>(this.attach_tbChamCongs), new Action<tbChamCong>(this.detach_tbChamCongs));
			this._tbDanhGias = new EntitySet<tbDanhGia>(new Action<tbDanhGia>(this.attach_tbDanhGias), new Action<tbDanhGia>(this.detach_tbDanhGias));
			this._tbDuAns = new EntitySet<tbDuAn>(new Action<tbDuAn>(this.attach_tbDuAns), new Action<tbDuAn>(this.detach_tbDuAns));
			this._tbChucVu = default(EntityRef<tbChucVu>);
			this._tbPhongBan = default(EntityRef<tbPhongBan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNhanVien", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maNhanVien
		{
			get
			{
				return this._maNhanVien;
			}
			set
			{
				if ((this._maNhanVien != value))
				{
					this.OnmaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._maNhanVien = value;
					this.SendPropertyChanged("maNhanVien");
					this.OnmaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenNV", DbType="NVarChar(150)")]
		public string tenNV
		{
			get
			{
				return this._tenNV;
			}
			set
			{
				if ((this._tenNV != value))
				{
					this.OntenNVChanging(value);
					this.SendPropertyChanging();
					this._tenNV = value;
					this.SendPropertyChanged("tenNV");
					this.OntenNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaysinh", DbType="Date NOT NULL")]
		public System.DateTime ngaysinh
		{
			get
			{
				return this._ngaysinh;
			}
			set
			{
				if ((this._ngaysinh != value))
				{
					this.OnngaysinhChanging(value);
					this.SendPropertyChanging();
					this._ngaysinh = value;
					this.SendPropertyChanged("ngaysinh");
					this.OnngaysinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdt", DbType="Int")]
		public System.Nullable<int> sdt
		{
			get
			{
				return this._sdt;
			}
			set
			{
				if ((this._sdt != value))
				{
					this.OnsdtChanging(value);
					this.SendPropertyChanging();
					this._sdt = value;
					this.SendPropertyChanged("sdt");
					this.OnsdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NVarChar(150)")]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taikhoan", DbType="NVarChar(50)")]
		public string taikhoan
		{
			get
			{
				return this._taikhoan;
			}
			set
			{
				if ((this._taikhoan != value))
				{
					this.OntaikhoanChanging(value);
					this.SendPropertyChanging();
					this._taikhoan = value;
					this.SendPropertyChanged("taikhoan");
					this.OntaikhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matkhau", DbType="NVarChar(50)")]
		public string matkhau
		{
			get
			{
				return this._matkhau;
			}
			set
			{
				if ((this._matkhau != value))
				{
					this.OnmatkhauChanging(value);
					this.SendPropertyChanging();
					this._matkhau = value;
					this.SendPropertyChanged("matkhau");
					this.OnmatkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maChucVu", DbType="Int")]
		public System.Nullable<int> maChucVu
		{
			get
			{
				return this._maChucVu;
			}
			set
			{
				if ((this._maChucVu != value))
				{
					if (this._tbChucVu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaChucVuChanging(value);
					this.SendPropertyChanging();
					this._maChucVu = value;
					this.SendPropertyChanged("maChucVu");
					this.OnmaChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maPhongBan", DbType="Int")]
		public System.Nullable<int> maPhongBan
		{
			get
			{
				return this._maPhongBan;
			}
			set
			{
				if ((this._maPhongBan != value))
				{
					if (this._tbPhongBan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaPhongBanChanging(value);
					this.SendPropertyChanging();
					this._maPhongBan = value;
					this.SendPropertyChanged("maPhongBan");
					this.OnmaPhongBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoatdong", DbType="Bit")]
		public System.Nullable<bool> hoatdong
		{
			get
			{
				return this._hoatdong;
			}
			set
			{
				if ((this._hoatdong != value))
				{
					this.OnhoatdongChanging(value);
					this.SendPropertyChanging();
					this._hoatdong = value;
					this.SendPropertyChanged("hoatdong");
					this.OnhoatdongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anh", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary anh
		{
			get
			{
				return this._anh;
			}
			set
			{
				if ((this._anh != value))
				{
					this.OnanhChanging(value);
					this.SendPropertyChanging();
					this._anh = value;
					this.SendPropertyChanged("anh");
					this.OnanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbNhanVien_tbChamCong", Storage="_tbChamCongs", ThisKey="maNhanVien", OtherKey="maNhanVien")]
		public EntitySet<tbChamCong> tbChamCongs
		{
			get
			{
				return this._tbChamCongs;
			}
			set
			{
				this._tbChamCongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbNhanVien_tbDanhGia", Storage="_tbDanhGias", ThisKey="maNhanVien", OtherKey="maNhanVien")]
		public EntitySet<tbDanhGia> tbDanhGias
		{
			get
			{
				return this._tbDanhGias;
			}
			set
			{
				this._tbDanhGias.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbNhanVien_tbDuAn", Storage="_tbDuAns", ThisKey="maNhanVien", OtherKey="maNhanVien")]
		public EntitySet<tbDuAn> tbDuAns
		{
			get
			{
				return this._tbDuAns;
			}
			set
			{
				this._tbDuAns.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbChucVu_tbNhanVien", Storage="_tbChucVu", ThisKey="maChucVu", OtherKey="maChucVu", IsForeignKey=true)]
		public tbChucVu tbChucVu
		{
			get
			{
				return this._tbChucVu.Entity;
			}
			set
			{
				tbChucVu previousValue = this._tbChucVu.Entity;
				if (((previousValue != value) 
							|| (this._tbChucVu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbChucVu.Entity = null;
						previousValue.tbNhanViens.Remove(this);
					}
					this._tbChucVu.Entity = value;
					if ((value != null))
					{
						value.tbNhanViens.Add(this);
						this._maChucVu = value.maChucVu;
					}
					else
					{
						this._maChucVu = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbChucVu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbPhongBan_tbNhanVien", Storage="_tbPhongBan", ThisKey="maPhongBan", OtherKey="maPhongBan", IsForeignKey=true)]
		public tbPhongBan tbPhongBan
		{
			get
			{
				return this._tbPhongBan.Entity;
			}
			set
			{
				tbPhongBan previousValue = this._tbPhongBan.Entity;
				if (((previousValue != value) 
							|| (this._tbPhongBan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbPhongBan.Entity = null;
						previousValue.tbNhanViens.Remove(this);
					}
					this._tbPhongBan.Entity = value;
					if ((value != null))
					{
						value.tbNhanViens.Add(this);
						this._maPhongBan = value.maPhongBan;
					}
					else
					{
						this._maPhongBan = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbPhongBan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbChamCongs(tbChamCong entity)
		{
			this.SendPropertyChanging();
			entity.tbNhanVien = this;
		}
		
		private void detach_tbChamCongs(tbChamCong entity)
		{
			this.SendPropertyChanging();
			entity.tbNhanVien = null;
		}
		
		private void attach_tbDanhGias(tbDanhGia entity)
		{
			this.SendPropertyChanging();
			entity.tbNhanVien = this;
		}
		
		private void detach_tbDanhGias(tbDanhGia entity)
		{
			this.SendPropertyChanging();
			entity.tbNhanVien = null;
		}
		
		private void attach_tbDuAns(tbDuAn entity)
		{
			this.SendPropertyChanging();
			entity.tbNhanVien = this;
		}
		
		private void detach_tbDuAns(tbDuAn entity)
		{
			this.SendPropertyChanging();
			entity.tbNhanVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbPhongBan")]
	public partial class tbPhongBan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maPhongBan;
		
		private string _tenPhongBan;
		
		private string _diachiPB;
		
		private EntitySet<tbNhanVien> _tbNhanViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaPhongBanChanging(int value);
    partial void OnmaPhongBanChanged();
    partial void OntenPhongBanChanging(string value);
    partial void OntenPhongBanChanged();
    partial void OndiachiPBChanging(string value);
    partial void OndiachiPBChanged();
    #endregion
		
		public tbPhongBan()
		{
			this._tbNhanViens = new EntitySet<tbNhanVien>(new Action<tbNhanVien>(this.attach_tbNhanViens), new Action<tbNhanVien>(this.detach_tbNhanViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maPhongBan", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maPhongBan
		{
			get
			{
				return this._maPhongBan;
			}
			set
			{
				if ((this._maPhongBan != value))
				{
					this.OnmaPhongBanChanging(value);
					this.SendPropertyChanging();
					this._maPhongBan = value;
					this.SendPropertyChanged("maPhongBan");
					this.OnmaPhongBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenPhongBan", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tenPhongBan
		{
			get
			{
				return this._tenPhongBan;
			}
			set
			{
				if ((this._tenPhongBan != value))
				{
					this.OntenPhongBanChanging(value);
					this.SendPropertyChanging();
					this._tenPhongBan = value;
					this.SendPropertyChanged("tenPhongBan");
					this.OntenPhongBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachiPB", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string diachiPB
		{
			get
			{
				return this._diachiPB;
			}
			set
			{
				if ((this._diachiPB != value))
				{
					this.OndiachiPBChanging(value);
					this.SendPropertyChanging();
					this._diachiPB = value;
					this.SendPropertyChanged("diachiPB");
					this.OndiachiPBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbPhongBan_tbNhanVien", Storage="_tbNhanViens", ThisKey="maPhongBan", OtherKey="maPhongBan")]
		public EntitySet<tbNhanVien> tbNhanViens
		{
			get
			{
				return this._tbNhanViens;
			}
			set
			{
				this._tbNhanViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbNhanViens(tbNhanVien entity)
		{
			this.SendPropertyChanging();
			entity.tbPhongBan = this;
		}
		
		private void detach_tbNhanViens(tbNhanVien entity)
		{
			this.SendPropertyChanging();
			entity.tbPhongBan = null;
		}
	}
}
#pragma warning restore 1591
