<?xml version="1.0" encoding="utf-8"?><Database Name="EmployeeManagement" Class="Employee_ManagementDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-S3C1RNO\SQLEXPRESS;Initial Catalog=EmployeeManagement;User ID=sa" SettingsObjectName="project_Employee_Management.Properties.Settings" SettingsPropertyName="EmployeeManagementConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbChamCong" Member="tbChamCongs">
    <Type Name="tbChamCong">
      <Column Name="maNgay" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="maNhanVien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ngaylamviec" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="trangthai" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="fulltime" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="tbNhanVien_tbChamCong" Member="tbNhanVien" ThisKey="maNhanVien" OtherKey="maNhanVien" Type="tbNhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbChucVu" Member="tbChucVus">
    <Type Name="tbChucVu">
      <Column Name="maChucVu" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tenChucVu" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="luongcung" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="huongDoanhSo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tbChucVu_tbNhanVien" Member="tbNhanViens" ThisKey="maChucVu" OtherKey="maChucVu" Type="tbNhanVien" />
    </Type>
  </Table>
  <Table Name="dbo.tbDanhGia" Member="tbDanhGias">
    <Type Name="tbDanhGia">
      <Column Name="maDanhGia" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="maNhanVien" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="mucDanhGia" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ngayDanhGia" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ghichu" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="tbNhanVien_tbDanhGia" Member="tbNhanVien" ThisKey="maNhanVien" OtherKey="maNhanVien" Type="tbNhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbDuAn" Member="tbDuAns">
    <Type Name="tbDuAn">
      <Column Name="maDuAn" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tenDuAn" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="maNhanVien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="giatri" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="trangthai" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="tbNhanVien_tbDuAn" Member="tbNhanVien" ThisKey="maNhanVien" OtherKey="maNhanVien" Type="tbNhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbNhanVien" Member="tbNhanViens">
    <Type Name="tbNhanVien">
      <Column Name="maNhanVien" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tenNV" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="ngaysinh" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sdt" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="diachi" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="taikhoan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="matkhau" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="maChucVu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="maPhongBan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="hoatdong" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="anh" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="tbNhanVien_tbChamCong" Member="tbChamCongs" ThisKey="maNhanVien" OtherKey="maNhanVien" Type="tbChamCong" />
      <Association Name="tbNhanVien_tbDanhGia" Member="tbDanhGias" ThisKey="maNhanVien" OtherKey="maNhanVien" Type="tbDanhGia" />
      <Association Name="tbNhanVien_tbDuAn" Member="tbDuAns" ThisKey="maNhanVien" OtherKey="maNhanVien" Type="tbDuAn" />
      <Association Name="tbChucVu_tbNhanVien" Member="tbChucVu" ThisKey="maChucVu" OtherKey="maChucVu" Type="tbChucVu" IsForeignKey="true" />
      <Association Name="tbPhongBan_tbNhanVien" Member="tbPhongBan" ThisKey="maPhongBan" OtherKey="maPhongBan" Type="tbPhongBan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbPhongBan" Member="tbPhongBans">
    <Type Name="tbPhongBan">
      <Column Name="maPhongBan" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tenPhongBan" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="diachiPB" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="tbPhongBan_tbNhanVien" Member="tbNhanViens" ThisKey="maPhongBan" OtherKey="maPhongBan" Type="tbNhanVien" />
    </Type>
  </Table>
</Database>